name: Build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - name: Install Lix
        uses: diogocastro/install-lix-action@f5e94192f565f53d84f41a056956dc0d3183b343
      - name: Build
        run: |
          nix build .# --out-link result
          mkdir -p dist
          cp -rL result/* dist/
      - name: Deploy to Git Pages
        uses: actions/git-pages@8f7ba32babc864c89992c47346c99888568d4105
        with:
          site: https://diogocastro.net/
          token: ${{ forge.token }}
          source: dist/
