name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: codeberg-tiny

    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: setup node
        uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c
        with:
          node-version: 24

      - name: install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with:
          version: 10
          run_install: false

      - name: install deps
        run: pnpm install --prod

      - name: build
        run: pnpm build

      - run: echo "diogocastro.net" > .domains

      - name: deploy to git-pages
        uses: actions/git-pages@065ca51993541b3e0d8a6becd93c627a9fee3584
        with:
          site: https://diogocastro.net/
          token: ${{ forge.token }}
          source: dist/
